/* eslint-env node */
/**
 * withDailySparkWidgets — Expo config plugin that adds Android Home-screen
 * widget support (AppWidgetProvider + layouts) to the iOS/Android projects
 * generated by `expo prebuild` / EAS Build (CNG).
 *
 * OPT-IN: this plugin is NOT registered in app.json by default. To enable it:
 *
 *   1. npm install react-native-android-widget  (optional; not required)
 *   2. uncomment the plugin entry in app.json:
 *        ["plugins/withDailySparkWidgets", {}]
 *   3. npx expo prebuild --platform android
 *   4. npx expo run:android   (development build)
 *
 * The plugin copies the widget sources under `widgets/android/` into the
 * generated android project. Requires a development build to test — widgets
 * do not run in Expo Go.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const WIDGET_PROVIDER = "com.dailyspark.quotes.widget.DailySparkWidgetProvider";

module.exports = function withDailySparkWidgets(config) {
  config = withAndroidManifest(config, (cfg) => {
    const receivers = cfg.modResults.manifest.application?.[0]?.receiver || [];
    const already = receivers.find((r) => r.$["android:name"] === WIDGET_PROVIDER);
    if (already) return cfg;

    const receiver = {
      $: {
        "android:name": WIDGET_PROVIDER,
        "android:exported": "false",
        "android:label": "Daily Spark Widget",
      },
      "intent-filter": [
        {
          action: [{ $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } }],
        },
      ],
      "meta-data": [
        {
          $: {
            "android:name": "android.appwidget.provider",
            "android:resource": "@xml/daily_spark_widget_info",
          },
        },
      ],
    };
    if (!cfg.modResults.manifest.application?.[0]) {
      cfg.modResults.manifest.application = [{ receiver: [receiver] }];
    } else {
      cfg.modResults.manifest.application[0].receiver = [
        ...cfg.modResults.manifest.application[0].receiver,
        receiver,
      ];
    }
    return cfg;
  });

  config = withDangerousMod(config, ["android", async (cfg) => {
    const androidRoot = cfg.modRequest.platformProjectRoot;
    const srcDir = path.resolve(__dirname, "..", "widgets", "android");
    copyDir(srcDir, androidRoot);
    return cfg;
  }]);

  return config;
};

/** Recursively copy a source directory into the android project. */
function copyDir(from, toRoot) {
  const entries = fs.readdirSync(from, { withFileTypes: true });
  for (const entry of entries) {
    const src = path.join(from, entry.name);
    const dest = path.join(toRoot, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(dest, { recursive: true });
      copyDir(src, dest);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(src, dest);
    }
  }
}